### ISSUE TITLE
Make ubuntu 16.04 docker image

### ISSUE THREAD

**Issue by AbdealiLoKo** [pywikibot-catfiles/docker-file-metadata#3]

**Comment by drtrigon** [comment]
Done in e1173c4. Currently building, see https://hub.docker.com/r/pywikibotcatfiles/docker-file-metadata/builds/bmzzr4rzreyurtq8x2nbtmh/

Had to switch from `openjdk-7-jre` to `openjdk-8-jre` nothing else. Hope this works for ZXing otherwise we have to go back by adding a ppa, confer http://askubuntu.com/questions/759451/how-can-i-install-openjdk-on-ubuntu-16-04

**Comment by AbdealiLoKo** [comment]
Zxing works with 6, 7 and 8 - so should be fine
